### ISSUE TITLE
TypeScript "Go To Source Definition" not working

### ISSUE THREAD

**Issue by niksy** [sublimelsp/LSP-vue#133]
It seems like [TypeScript’s "Go To Source Definition"](https://github.com/sublimelsp/LSP-typescript#goto-source-definition-command) is not working when used in Vue SFC, but the same functionality on same imports works in regular .ts files.

There were some resolved issues in @vue/language-tools repository related to hybrid mode support which suggest that this was fixed in v2, but even with using [settings for TypeScript plugin](https://github.com/sublimelsp/LSP-vue/issues/130#issuecomment-2460757940) it doesn’t seem to work. The only difference I’ve found is that using hybrid mode activates real TypeScript LSP so you get information "No source definitions found" when using command in Vue files (expected since this is coming from language server using Vue plugin).

I don’t know if this is TypeScript or Vue related, haven’t found anything specific that would suggest this shouldn’t work in Vue files.

**Comment by niksy** [comment]
Latest Vue and TypeScript.

I can’t reproduce it consistently. For example, running fresh Vite app with Vue and TypeScript doesn’t have this error, but on the larger project I work on I get the following error:

```
:: [19:40:48.635] --> LSP-typescript workspace/executeCommand (12): {'command': '_typescript.goToSourceDefinition', 'arguments': ['file://root/file.vue', {'character': 28, 'line': 24}], 'workDoneToken': '$ublime-work-done-progress-12'}
:: [19:40:48.637] <-  LSP-typescript $/progress: {'token': '$ublime-work-done-progress-12', 'value': {'kind': 'begin', 'title': 'Finding source definitions…'}}
:: [19:40:48.648] <~~ LSP-typescript (12) (duration: 12ms): {'code': 1, 'message': "<semantic> TypeScript Server Error (5.9.3)\nCannot read properties of undefined (reading 'getSourceFile')\nTypeError: Cannot read properties of undefined (reading 'getSourceFile')\n    at getValidSourceFile (root/node_modules/typescript/lib/typescript.js:152747:32)\n    at Object.getDefinitionAtPosition2 [as getDefinitionAtPosition] (root/node_modules/typescript/lib/typescript.js:153285:71)\n    at IpcIOSession.findSourceDefinition (root/node_modules/typescript/lib/typescript.js:195284:38)\n    at findSourceDefinition (root/node_modules/typescript/lib/typescript.js:194182:43)\n    at root/node_modules/typescript/lib/typescript.js:196832:15\n    at IpcIOSession.executeWithRequestId (root/node_modules/typescript/lib/typescript.js:196821:14)\n    at IpcIOSession.executeCommand (root/node_modules/typescript/lib/typescript.js:196830:29)\n    at IpcIOSession.onMessage (root/node_modules/typescript/lib/typescript.js:196878:68)\n    at process.<anonymous> (root/node_modules/typescript/lib/_tsserver.js:519:14)\n    at process.emit (node:events:518:28)\n    at emit (node:internal/child_process:950:14)\n    at process.processTicksAndRejections (node:internal/process/task_queues:91:21)"}
```

I’ve tried with the same TS config options, smaller Vue files, disabling other LSPs and leaving only LSP-vue and LSP-typescript, but nothing works.

**Comment by rchl** [comment]
I wouldn't be surprised if it also reproduces in VSCode in which case it should be reported in Vue Language Server repo.
