### ISSUE TITLE
Error:No module named 'LSP'

### ISSUE THREAD

**Issue by jingyuexing** [sublimelsp/LSP-vue#71]
Traceback (most recent call last):
  File "D:\sublime_text_3211\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "D:\sublime_text_3211\sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "D:\sublime_text_3211\Data\Installed Packages\LSP-vue.sublime-package\plugin.py", line 3, in <module>
  File "D:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\__init__.py", line 11, in <module>
    from .npm_client_handler import NpmClientHandler
  File "D:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\npm_client_handler.py", line 3, in <module>
    from LSP.plugin.core.handlers import LanguageHandler
ImportError: No module named 'LSP'

**Comment by jingyuexing** [comment]
Traceback (most recent call last):
  File "D:\sublime_text_3211\sublime_plugin.py", line 298, in on_api_ready
    plc()
  File "D:\sublime_text_3211\Data\Installed Packages\LSP-vue.sublime-package\plugin.py", line 7, in plugin_loaded
    LspVuePlugin.setup()
  File "D:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\npm_client_handler.py", line 64, in setup
    cls.__server.setup()
  File "D:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\server_npm_resource.py", line 70, in setup
    self._copy_to_cache()
  File "D:\SUBLIM~2\Data\Packages\LSP_UT~1\st3\lsp_utils\server_npm_resource.py", line 94, in _copy_to_cache
    ResourcePath(src_path).copytree(cache_server_path, exist_ok=True)
  File "D:\SUBLIM~2\Data\Packages\SUBLIM~3\st3\sublime_lib\resource_path.py", line 605, in copytree
    for resource in self.rglob('*'):
  File "D:\SUBLIM~2\Data\Packages\SUBLIM~3\st3\sublime_lib\resource_path.py", line 545, in rglob
    return self.glob('**/' + pattern)
  File "D:\SUBLIM~2\Data\Packages\SUBLIM~3\st3\sublime_lib\resource_path.py", line 532, in glob
    return ResourcePath.glob_resources(base + pattern)
  File "D:\SUBLIM~2\Data\Packages\SUBLIM~3\st3\sublime_lib\resource_path.py", line 199, in glob_resources
    cls(path) for path in sublime.find_resources('')
  File "D:\SUBLIM~2\Data\Packages\SUBLIM~3\st3\sublime_lib\resource_path.py", line 200, in <listcomp>
    if match(path)
  File "D:\SUBLIM~2\Data\Packages\SUBLIM~3\st3\sublime_lib\_util\glob.py", line 42, in <lambda>
    return lambda s: (expr.search(s) is not None)

**Comment by rchl** [comment]
Read installation instructions please
https://github.com/sublimelsp/LSP-vue#installation
